from datetime import datetime

def generate_report(patient_id, bpm, diagnosis):

    report = f"""
SMART ECG REPORT
=================

Patient ID : {patient_id}
Date       : {datetime.now()}

Heart Rate : {bpm} BPM
Diagnosis  : {diagnosis}

Status : Automatically generated by SmartECG AI System
"""

    file = f"reports/{patient_id}.txt"

    with open(file,"w") as f:
        f.write(report)

    return file